version: 2
updates:
  # Flutter/Dart dependencies
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "hyminix"
    assignees:
      - "hyminix"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 3
    reviewers:
      - "hyminix"
    assignees:
      - "hyminix"
    commit-message:
      prefix: "ci"
      include: "scope"

  # Gradle dependencies (Android)
  - package-ecosystem: "gradle"
    directory: "/android"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 3
    reviewers:
      - "hyminix"
    assignees:
      - "hyminix"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"